# Data migration -- NOT generated by makemigrations.
#
# Required for the app to function at all: wallet/signals.py's create_wallet
# signal runs on every User post_save (created=True) and does
# Token.objects.get(name="bitcoin"/"ethereum"/"tether"). With an empty Token
# table this raises Token.DoesNotExist -- so even `manage.py createsuperuser`
# on a fresh database crashes without this seed data. wallet/tasks/periodic
# also expects rows for the remaining coins in its TOKENS list.
#
# actual_price is seeded at 0.0; the periodic django-q tasks
# (download_historical_data / daily_data_download) backfill real prices from
# CoinGecko once someone schedules them -- see APP_CHANGES.md, they are
# not scheduled anywhere in the upstream app.
from django.db import migrations

TOKENS = [
    ("bitcoin", "BTC"),
    ("ethereum", "ETH"),
    ("tether", "USDT"),
    ("binancecoin", "BNB"),
    ("solana", "SOL"),
    ("cardano", "ADA"),
]


def seed_tokens(apps, schema_editor):
    Token = apps.get_model("wallet", "Token")
    for name, symbol in TOKENS:
        Token.objects.get_or_create(
            name=name,
            defaults={"symbol": symbol, "actual_price": 0.0},
        )


def unseed_tokens(apps, schema_editor):
    Token = apps.get_model("wallet", "Token")
    Token.objects.filter(name__in=[name for name, _ in TOKENS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_alter_wallet_owner_alter_wallet_token"),
    ]

    operations = [
        migrations.RunPython(seed_tokens, unseed_tokens),
    ]
